- name: Install password manager tools
  hosts: all
  tasks: 
    - name: Install Bitwarden
      win_chocolatey:
        name: bitwarden

- name: Install communication apps
  hosts: all
  tasks: 
    - name: Install Discord
      win_chocolatey:
        name: discord
    - name: Install Wechat
      win_chocolatey:
        name: wechat

- name: Install gaming platform
  hosts: all
  tasks: 
    - name: Install Steam
      win_chocolatey:
        name: steam-client
