- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  hosts: all
  tasks: 
   - name: Install chocolatey
     win_chocolatey:
       name: chocolatey

- name: Install version control tools
  hosts: all
  tasks: 
    - name: Install Git
      win_chocolatey:
        name: git
        state: present

- name: Install programming language supports (node, python)
  hosts: all
  tasks: 
    - name: Install Node
      win_chocolatey:
        name: git
        state: present

    - name: Install Python3
      win_chocolatey:
        name: nodejs
        state: present

- name: Install terminal
  hosts: all
  tasks: 
    - name: Install windows ternimal
      win_chocolatey:
        name: microsoft-windows-terminal

- name: Install editors
  hosts: all
  tasks: 
    - name: Install vscode
      win_chocolatey:
        name: vscode
        state: present

    - name: Install neovim
      win_chocolatey:
        name: neovim
        state: present
    
