- name: Test connection
  hosts: all
  tasks:
    - name: Ping
      win_ping:
    - name: Show whoami
      ansible.windows.win_command: whoami
      register: whoami
    - debug: var=whoami.stdout 


- name: Install password manager tools
  hosts: all
  tasks: 
    - name: Install 1password
      win_chocolatey:
        name: 1password
    - name: Install Bitwarden
      win_chocolatey:
        name: bitwarden

- name: Install communication apps
  hosts: all
  tasks: 
    - name: Install Microsoft Teams
      win_chocolatey:
        name: microsoft-teams
    - name: Install Slack
      win_chocolatey:
        name: slack

